---
- name: Allow outgoing HTTPS
  ansible.builtin.iptables:
    comment: "Allow outgoing HTTPS"
    chain: OUTPUT
    out_interface: "{{ interface }}"
    protocol: tcp
    destination_port: 443
    match:
      - tcp
      - conntrack
    ctstate:
      - NEW
      - ESTABLISHED
    jump: "{{ jump }}"
#
# - name: Allow incoming HTTPS
#  ansible.builtin.iptables:
#    comment: "Allow incoming HTTPS"
#    chain: INPUT
#    in_interface: "{{ interface }}"
#    protocol: tcp
#    source_port: 443
#    match:
#      - state
#      - tcp
#    ctstate:
#      - ESTABLISHED
#    jump: "{{ jump }}"
