---
- name: Allow outgoing SSH
  ansible.builtin.iptables:
    comment: "Allow outgoing SSH"
    chain: OUTPUT
    out_interface: "{{ interface }}"
    protocol: tcp
    destination_port: 22
    match:
      - tcp
      - conntrack
    ctstate:
      - NEW
      - ESTABLISHED
    jump: "{{ jump }}"
