---
- name: Enable incoming connection tracking
  ansible.builtin.iptables:
    comment: "Enable incoming connection tracking"
    chain: INPUT
    match:
      - state
    ctstate:
      - ESTABLISHED
      - RELATED
    jump: "{{ jump }}"

- name: Enable outgoing connection tracking
  ansible.builtin.iptables:
    comment: "Enable outgoing connection tracking"
    chain: OUTPUT
    match:
      - state
    ctstate:
      - ESTABLISHED
      - RELATED
    jump: "{{ jump }}"

