---
- name: Drop XMAS packets
  ansible.builtin.iptables:
    comment: "Drop XMAS packets"
    chain: INPUT
    protocol: tcp
    match:
      - conntrack
    tcp_flags:
      flags: ALL
      flags_set:
        - ACK
        - RST
        - SYN
        - FIN
    jump: DROP