---
- name: Drop null packets
  ansible.builtin.iptables:
    comment: "Drop null packets"
    chain: INPUT
    # in_interface: "{{ interface }}"
    protocol: tcp
    match:
      - state
      - conntrack
    tcp_flags:
      flags: NONE
      flags_set:
        - ACK
        - RST
        - SYN
        - FIN
    jump: DROP