---
- name: Force SYN packet check
  ansible.builtin.iptables:
    comment: "Force SYN packet check"
    chain: INPUT
    protocol: tcp
    match:
      - state
      - conntrack
    ctstate:
      - NEW
    jump: DROP