---
- name: Force SYN packet check
  ansible.builtin.iptables:
    comment: "Force SYN packet check"
    chain: INPUT
    protocol: tcp
    match:
      - conntrack
      - state
    ctstate:
      - NEW
    jump: DROP