---
- name: Allow incoming FTP-CONTROL
  ansible.builtin.iptables:
    comment: "Allow incoming FTP-CONTROL"
    chain: INPUT
    in_interface: "{{ interface }}"
    protocol: tcp
    destination_port: 21
    match:
      - state
      - conntrack
      - tcp
    ctstate:
      - ESTABLISHED
    jump: "{{ jump }}"
