---
- name: Allow incoming FTP-DATA
  ansible.builtin.iptables:
    comment: "Allow incoming FTP-DATA"
    chain: INPUT
    in_interface: "{{ interface }}"
    protocol: tcp
    source_port: 20
    match:
      - conntrack
      - state
      - tcp
    ctstate:
      - ESTABLISHED
      - RELATED
    jump: "{{ jump }}"
