---
- name: Allow outgoing FTP-CONTROL
  ansible.builtin.iptables:
    comment: "Allow outgoing FTP-CONTROL"
    chain: OUTPUT
    out_interface: "{{ interface }}"
    protocol: tcp
    destination_port: 21
    match:
      - state
      - conntrack
      - tcp
    ctstate:
      - NEW
      - ESTABLISHED
    jump: "{{ jump }}"
