---
- name: Allow outgoing HTTP
  ansible.builtin.iptables:
    comment: "Allow outgoing HTTP"
    chain: OUTPUT
    out_interface: "{{ interface }}"
    protocol: tcp
    destination_port: 80
    match:
      - state
      - tcp
    ctstate:
      - NEW
      - ESTABLISHED
    jump: "{{ jump }}"

- name: Allow incoming HTTP
  ansible.builtin.iptables:
    comment: "Allow incoming HTTP"
    chain: INPUT
    in_interface: "{{ interface }}"
    protocol: tcp
    source_port: 80
    match:
      - state
      - tcp
    ctstate:
      - ESTABLISHED
    jump: "{{ jump }}"
