---
- name: Allow incoming IMAP
  ansible.builtin.iptables:
    comment: "Allow incoming IMAP"
    chain: INPUT
    in_interface: "{{ interface }}"
    protocol: tcp
    destination_port: 143
    match:
      - state
      - tcp
      - conntrack
    ctstate:
      - NEW
      - ESTABLISHED
    jump: "{{ jump }}"
#
# - name: Allow outgoing IMAP
#  ansible.builtin.iptables:
#    comment: "Allow outgoing IMAP"
#    chain: OUTPUT
#    out_interface: "{{ interface }}"
#    protocol: tcp
#    source_port: 143
#    match:
#      - state
#      - tcp
#    ctstate:
#      - ESTABLISHED
#    jump: "{{ jump }}"
