---
- name: Allow IMAP
  ansible.builtin.iptables:
    comment: "Allow IMAP"
    chain: INPUT
    in_interface: "{{ interface }}"
    protocol: tcp
    destination_port: 143
    match:
      - state
      - tcp
    ctstate:
      - NEW
      - ESTABLISHED
    jump: "{{ jump }}"

- name: Allow IMAP
  ansible.builtin.iptables:
    comment: "Allow IMAP"
    chain: OUTPUT
    out_interface: "{{ interface }}"
    protocol: tcp
    source_port: 143
    match:
      - state
      - tcp
    ctstate:
      - ESTABLISHED
    jump: "{{ jump }}"
