---
- name: Allow incoming IMAPS
  ansible.builtin.iptables:
    comment: "Allow incoming IMAPS"
    chain: INPUT
    in_interface: "{{ interface }}"
    protocol: tcp
    destination_port: 993
    match:
      - state
      - tcp
      - conntrack
    ctstate:
      - NEW
      - ESTABLISHED
    jump: "{{ jump }}"
#
# - name: Allow outgoing IMAPS
#  ansible.builtin.iptables:
#    comment: "Allow outgoing IMAPS"
#    chain: OUTPUT
#    out_interface: "{{ interface }}"
#    protocol: tcp
#    source_port: 993
#    match:
#      - state
#      - tcp
#    ctstate:
#      - ESTABLISHED
#    jump: "{{ jump }}"
