---
- name: Allow outgoing IMAPS
  ansible.builtin.iptables:
    comment: "Allow outgoing IMAPS"
    chain: OUTPUT
    out_interface: "{{ interface }}"
    protocol: tcp
    source_port: 993
    match:
      - tcp
      - conntrack
    ctstate:
      - ESTABLISHED
    jump: "{{ jump }}"
