---
- name: Allow outgoing IMAP
  ansible.builtin.iptables:
    comment: "Allow outgoing IMAP"
    chain: OUTPUT
    out_interface: "{{ interface }}"
    protocol: tcp
    source_port: 143
    match:
      - state
      - tcp
      - conntrack
    ctstate:
      - ESTABLISHED
    jump: "{{ jump }}"
