---
- name: Allow outgoing postgres
  ansible.builtin.iptables:
    comment: "Allow outgoing postgres"
    chain: OUTPUT
    out_interface: "{{ interface }}"
    protocol: tcp
    destination_port: 5432
    match:
      - state
      - tcp
      - conntrack
    ctstate:
      - NEW
      - ESTABLISHED
    jump: "{{ jump }}"
#
#- name: Allow incoming postgres
#  ansible.builtin.iptables:
#    comment: "Allow incoming postgres"
#    chain: INPUT
#    in_interface: "{{ interface }}"
#    protocol: tcp
#    source_port: 5432
#    match:
#      - state
#      - tcp
#    ctstate:
#      - ESTABLISHED
#    jump: "{{ jump }}"
