---
- name: Allow outgoing SSH
  ansible.builtin.iptables:
    comment: "Allow outgoing SSH"
    chain: OUTPUT
    out_interface: "{{ interface }}"
    protocol: tcp
    destination_port: 22
    match:
      - state
      - tcp
    ctstate:
      - NEW
      - ESTABLISHED
    jump: "{{ jump }}"

- name: Allow incoming SSH
  ansible.builtin.iptables:
    comment: "Allow incoming SSH"
    chain: INPUT
    in_interface: "{{ interface }}"
    protocol: tcp
    source_port: 22
    match:
      - state
      - tcp
    ctstate:
      - ESTABLISHED
    jump: "{{ jump }}"
