---
- name: Allow incoming POP3
  ansible.builtin.iptables:
    comment: "Allow incoming POP3"
    chain: INPUT
    in_interface: "{{ interface }}"
    protocol: tcp
    destination_port: 110
    match:
      - state
      - tcp
      - conntrack
    ctstate:
      - NEW
      - ESTABLISHED
    jump: "{{ jump }}"
#
# - name: Allow outgoing POP3
#  ansible.builtin.iptables:
#    comment: "Allow outgoing POP3"
#    chain: OUTPUT
#    out_interface: "{{ interface }}"
#    protocol: tcp
#    source_port: 110
#    match:
#      - state
#      - tcp
#    ctstate:
#      - ESTABLISHED
#    jump: "{{ jump }}"
