---
- name: Allow outgoing POP3S
  ansible.builtin.iptables:
    comment: "Allow outgoing POP3S"
    chain: OUTPUT
    out_interface: "{{ interface }}"
    protocol: tcp
    source_port: 995
    match:
      - state
      - tcp
      - conntrack
    ctstate:
      - ESTABLISHED
    jump: "{{ jump }}"
