---
- name: Allow POP3
  ansible.builtin.iptables:
    comment: "Allow POP3"
    chain: INPUT
    in_interface: "{{ interface }}"
    protocol: tcp
    destination_port: 110
    match:
      - state
      - tcp
    ctstate:
      - NEW
      - ESTABLISHED
    jump: "{{ jump }}"

- name: Allow POP3
  ansible.builtin.iptables:
    comment: "Allow POP3"
    chain: OUTPUT
    out_interface: "{{ interface }}"
    protocol: tcp
    source_port: 110
    match:
      - state
      - tcp
    ctstate:
      - ESTABLISHED
    jump: "{{ jump }}"
