---
- name: Allow outgoing POP3
  ansible.builtin.iptables:
    comment: "Allow outgoing POP3"
    chain: OUTPUT
    out_interface: "{{ interface }}"
    protocol: tcp
    source_port: 110
    match:
      - state
      - tcp
      - conntrack
    ctstate:
      - ESTABLISHED
    jump: "{{ jump }}"
