- name: Allow outgoing Postgres
  ansible.builtin.iptables:
    comment: "Allow outgoing Postgres"
    chain: OUTPUT
    protocol: tcp
    out_interface: "{{ interface }}"
    source_port: "{{ port }}"
    match:
      - conntrack
      - state
      - tcp
    ctstate:
      - ESTABLISHED
    jump: "{{ jump }}"
