---
- name: incoming postgres subnet port
  ansible.builtin.iptables:
    comment: "incoming postgres subnet port"
    chain: INPUT
    in_interface: "{{ interface }}"
    protocol: tcp
    destination_port: "{{ port }}"
    source: "{{ subnet }}"
    match:
      - state
      - tcp
    ctstate:
      - NEW
      - ESTABLISHED
    jump: "{{ jump }}"

- name: incoming postgres subnet port
  ansible.builtin.iptables:
    comment: "incoming postgres subnet port"
    chain: OUTPUT
    protocol: tcp
    out_interface: "{{ interface }}"
    source_port: "{{ port }}"
    match:
      - state
      - tcp
    ctstate:
      - ESTABLISHED
    jump: "{{ jump }}"
