---
- name: Allow incoming Postgres
  ansible.builtin.iptables:
    comment: "Allow incoming Postgres"
    chain: INPUT
    in_interface: "{{ interface }}"
    protocol: tcp
    destination_port: "{{ port }}"
    source: "{{ subnet }}"
    match:
      - state
      - tcp
      - conntrack
    ctstate:
      - NEW
      - ESTABLISHED
    jump: "{{ jump }}"
#
# - name: Allow outgoing Postgres
#  ansible.builtin.iptables:
#    comment: "Allow outgoing Postgres"
#    chain: OUTPUT
#    protocol: tcp
#    out_interface: "{{ interface }}"
#    source_port: "{{ port }}"
#    match:
#      - state
#      - tcp
#    ctstate:
#      - ESTABLISHED
#    jump: "{{ jump }}"
