---
- name: Allow Sendmail or Postfix
  ansible.builtin.iptables:
    comment: "Allow Sendmail or Postfix"
    chain: INPUT
    in_interface: "{{ interface }}"
    protocol: tcp
    destination_port: 25
    match:
      - state
      - tcp
    ctstate:
      - NEW
      - ESTABLISHED
    jump: "{{ jump }}"

- name: Allow ALL incoming SSH
  ansible.builtin.iptables:
    comment: "Allow ALL incoming SSH"
    chain: OUTPUT
    out_interface: "{{ interface }}"
    protocol: tcp
    source_port: 25
    match:
      - state
      - tcp
    ctstate:
      - ESTABLISHED
    jump: "{{ jump }}"
