---
- name: Allow incoming SMTP
  ansible.builtin.iptables:
    comment: "Allow incoming SMTP"
    chain: INPUT
    in_interface: "{{ interface }}"
    protocol: tcp
    destination_port: "25, 465. 587"
    match:
      - state
      - tcp
    ctstate:
      - NEW
      - ESTABLISHED
    jump: "{{ jump }}"
#
#- name: Allow outgoing SMTP
#  ansible.builtin.iptables:
#    comment: "Allow outgoing SMTP"
#    chain: OUTPUT
#    out_interface: "{{ interface }}"
#    protocol: tcp
#    source_port: 25
#    match:
#      - state
#      - tcp
#    ctstate:
#      - ESTABLISHED
#    jump: "{{ jump }}"
