---
- name: Allow outgoing SMTP
  ansible.builtin.iptables:
    comment: "Allow outgoing SMTP"
    chain: OUTPUT
    out_interface: "{{ interface }}"
    protocol: tcp
    source_port: 25
    match:
      - state
      - tcp
    ctstate:
      - ESTABLISHED
    jump: "{{ jump }}"
