---
- name: copy arrow files
  hosts: rs-dba*
  gather_facts: false
  vars_files:
    - "../vars/index.yml"
  remote_user: "{{ username }}"
  strategy: free
  vars:
    pg2arrow_repo: rs-pg2arrow
    streamer_repo: rs-streamer
    str_priv: "{{ groups['all'] | select('match', '^rs-str') | map('extract', hostvars, ['private_ipv4']) | list | first }}"
  tasks:
    - name: copy arrow files from dba to str
      ansible.builtin.shell:
        cmd: scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i ~/.ssh/id_rsa {{ [app_dir, pg2arrow_repo] | path_join }}/*.arrow {{ username }}@{{ str_priv }}:{{ [app_dir, streamer_repo] | path_join }}/app/.
      register: scp_return
      changed_when: scp_return.rc != 0
