---
- name: Install Docker
  hosts: all,!data*
  vars_files:
    - "../vars/index.yml"
    - "../vars/docker.yml"
  remote_user: "{{ username }}"
  become: true
  roles:
    - geerlingguy.docker
    - gantsign.ctop
  tasks:
    - name: Install containerd.io docker-compose-plugin
      ansible.builtin.apt:
        pkg:
          - containerd.io
          - docker-compose-plugin
          - python3-docker
          - python3-pip

    - name: Install multi python packages with version specifiers
      ansible.builtin.pip:
        name:
          - jsondiff
          - pyyaml

    - name: Add user to docker group
      ansible.builtin.user:
        name: "{{ username }}"
        groups: docker
      become: true

    - name: Enable docker.service service
      ansible.builtin.systemd:
        name: docker.service
        enabled: true
      become: true

    - name: Enable containerd.service service
      ansible.builtin.systemd:
        name: containerd.service
        enabled: true
      become: true

    - name: Reset ssh connection to allow user changes to affect ansible user
      ansible.builtin.meta:
        reset_connection
