---
- name: Login registry
  hosts: all,!data*
  gather_facts: false
  vars_files:
    - "../vars/index.yml"
  remote_user: "{{ username }}"

  tasks:
  ### we need to add this config to manage
    - name: Login to Docker registry
      community.docker.docker_login:
        registry: registry.sw.frogtech.dev
        username: admin
        password: only4you
