---
- name: setup pg2arrow
  hosts: rs-dba*
  gather_facts: false
  vars_files:
    - "../vars/index.yml"
  vars:
    repo_name: rs-pg2arrow
    dba_priv: "{{ groups['all'] | select('match', '^rs-dba') | map('extract', hostvars, ['private_ipv4']) | list | first }}"

  remote_user: "{{ username }}"
  tasks:
    - name: Install postgres packages
      ansible.builtin.apt:
        name:
          - libcairo2-dev
          - pkg-config
        state: present
      become: true

    - name: Install {{ repo_name }} python requirements
      ansible.builtin.pip:
        requirements: "{{ [app_dir, repo_name] | path_join }}/requirements.txt"

    - name: copy env
      ansible.builtin.copy:
        mode: 0600
        src: "{{ [app_dir, repo_name] | path_join }}/.env.example"
        dest: "{{ [app_dir, repo_name] | path_join }}/.env"
        remote_src: true

    - name: Remove file production
      ansible.builtin.file:
        path: "{{ [app_dir, repo_name] | path_join }}/.env.example"
        state: absent

    # - name: Remove file development
    #   ansible.builtin.file:
    #     path: "{{ [app_dir, repo_name] | path_join }}/.env.development"
    #     state: absent

    - name: set DATABASE_URL in .env
      lineinfile:
        path: "{{ [app_dir, repo_name] | path_join }}/.env"
        regexp: "^DATABASE_URL="
        line: 'DATABASE_URL="postgresql://{{ username }}:{{ username }}@{{ dba_priv }}:5432/{{ username }}back"'
