---
- name: setup b2f
  hosts: rs-dba*
  gather_facts: false
  vars_files:
    - "../vars/index.yml"
  remote_user: "{{ username }}"
  vars:
    repo_name: rs-b2f
    dba_priv: "{{ groups['all'] | select('match', '^rs-dba') | map('extract', hostvars, ['private_ipv4']) | list | first }}"

  tasks:
    - name: Install {{ repo_name }}
      community.general.yarn:
        executable: /usr/local/lib/npm/bin/yarn
        path: "{{ [app_dir, repo_name] | path_join }}"
      become: false

    - name: copy env
      ansible.builtin.copy:
        mode: 0600
        src: "{{ [app_dir, repo_name] | path_join }}/.env.example"
        dest: "{{ [app_dir, repo_name] | path_join }}/.env"
        remote_src: true

    - name: set DATABASE_URL in .env
      lineinfile:
        path: "{{ [app_dir, repo_name] | path_join }}/.env"
        regexp: "^DATABASE_URL="
        line: 'DATABASE_URL="postgresql://{{ username }}:{{ username }}@{{ dba_priv }}:5432/{{ username }}front"'

    - name: set DATABASE_URL in .env
      lineinfile:
        path: "{{ [app_dir, repo_name] | path_join }}/.env"
        regexp: "^BACK_DATABASE_URL="
        line: 'BACK_DATABASE_URL="postgresql://{{ username }}:{{ username }}@{{ dba_priv }}:5432/{{ username }}back"'
