version: '3.8'

services:
  grafana:
    image: grafana/grafana:latest
    user: "1000"
    environment:
      GF_SERVER_DOMAIN: grafana.sw.frogtech.dev
      GF_SERVER_ROOT_URL: https://grafana.sw.frogtech.dev
      GF_DATABASE_TYPE: postgres
      GF_DATABASE_HOST: data-01:5432
      GF_DATABASE_NAME: grafana
      GF_DATABASE_USER: swarm
      GF_DATABASE_PASSWORD: swarm
      GF_REMOTE_CACHE_TYPE: redis
      GF_REMOTE_CACHE_CONNSTR: addr=data-01:6379,pool_size=100,db=0,ssl=false
    volumes:
      - /etc/hosts:/etc/hosts
      - /mnt/storage-pool/grafana:/var/lib/grafana
    networks:
      - traefik_public
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.grafana.entrypoints=https
        # - traefik.http.routers.grafana.middlewares=admin-auth
        - traefik.http.services.grafana.loadbalancer.server.port=3000
      placement:
        constraints:
          - node.role == manager

networks:
  traefik_public:
    external: true