version: '3.8'

services:
  app:
    image: registry.sw.frogtech.dev/rs-web:latest
    networks:
      - traefik_public
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.rsweb.entrypoints=https
        - traefik.http.services.rsweb.loadbalancer.server.port=3000
        - traefik.http.routers.rsweb.rule=Host(`frogtech.dev`)
      placement:
        constraints:
          - node.labels.environment == production

networks:
  traefik_public:
    external: true
