---
- name: Setup back
  hosts: manager*
  gather_facts: false
  vars_files:
    - "../vars/index.yml"
    - "../vars/sensitive.yml"
  remote_user: "{{ username }}"
  tasks:
    - name: Create /mnt/storage-pool directory
      ansible.builtin.file:
        path: /mnt/storage-pool
        state: directory
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: '0744'
      become: true
