---
- name: setup back
  hosts: rs-dba*
  gather_facts: false
  vars_files:
    - "../vars/index.yml"
  vars:
    repo_name: rs-back
    dba_priv: "{{ groups['all'] | select('match', '^rs-dba') | map('extract', hostvars, ['private_ipv4']) | list | first }}"
  remote_user: "{{ username }}"
  tasks:
    - name: echo PATH
      ansible.builtin.command: chdir={{ [app_dir, repo_name] | path_join }} python3 -m prisma generate
      register: res
      become: false
      environment:
        PATH: "{{ ansible_env.PATH }}:/home/regshort/.local/bin"
    - name: debug
      debug: msg="{{ res }}"
