---
- name: Setup back
  hosts: localhost
  vars_files:
    - "../vars/index.yml"
  tasks:
    - name: Copy prometheus-stack config
      ansible.builtin.template:
        src: "../apps/prometheus/prometheus-stack.yml.j2"
        dest: ~/prometheus-stack.yml
        mode: '0644'
