---
- name: debug
  hosts: localhost
  vars_files:
    - "../vars/index.yml"
  remote_user: root

  tasks:
    # cannot find good info online on how to change interfaces with ansible so i won't do it for now
    # - name: Rename external interface
    #   command: "ip link set {{ item }} name eth1"
    #   loop: "{{ ansible_interfaces }}"
    #   when: item is match('^et')
    #   become: true

    # - name: Rename internal interface
    #   command: "ip link set {{ item }} name ens20"
    #   loop: "{{ ansible_interfaces }}"
    #   when: item is match('^en')
    #   become: true

    - name: show current state of the firewall
      ansible.builtin.debug:
        msg: "{{ groups['all'] | select('match', '^rs-web') | map('extract', hostvars, ['private_ipv4']) | list | first }}"
