---
- name: Setup back
  hosts: manager*
  gather_facts: false
  vars_files:
    - "../vars/index.yml"
    - "../vars/sensitive.yml"
  remote_user: "{{ username }}"
  tasks:
    - name: Generate encrypted password
      shell: openssl passwd -apr1 only4you
      register: encrypted_password

    - name: Start traefik
      ansible.builtin.command:
        cmd: docker stack deploy -c ~/traefik-stack.yml traefik
      environment:
        HASHED_PASSWORD: "{{ encrypted_password.stdout }}"