---
- name: setup back
  hosts: localhost
  gather_facts: false
  vars_files:
    - "../vars/index.yml"
  remote_user: "{{ username }}"
  tasks:
    - name: add old tag to old servers
      debug:
        msg: "{{ item.key }}"
      when: not item.key.startswith('rs-controller')
      with_items: "{{ hostvars | dict2items }}"
