---
- name: Change root Password
  hosts: all
  gather_facts: false
  remote_user: root
  vars_files:
    - "../vars/index.yml"
    - "../vars/sensitive-deploy.yml"
  vars:
    new_password: "root-{{ inventory_hostname.split('-')[:2] | join('-') }}{{ seed_pass }}"
  tasks:
    - name: Createpw
      ansible.builtin.user:
        name: root
        state: present
        password: "{{ new_password | password_hash('sha512') }}"
