---
- name: Install gluster server
  hosts: data*
  vars_files:
    - "../vars/index.yml"
    - "../vars/glusterfs.yml"
  remote_user: "{{ unix_user }}"
  become: true
  roles:
    - geerlingguy.glusterfs
  tasks:
    - name: Find HC_Volume_* folders in /mnt/
      ansible.builtin.find:
        paths: /mnt/
        file_type: directory
        patterns: HC_Volume_*
      register: found_folders

    - name: Create /mnt/HC_Volume_data directory
      ansible.builtin.file:
        path: /mnt/{{ hc_name }}
        state: directory
        owner: "{{ unix_user }}"
        group: "{{ unix_user }}"
        mode: '0744'
      become: true


    - name: Replace mount point path in fstab
      ansible.builtin.lineinfile:
        path: /etc/fstab
        regexp: '^/dev/disk/by-id/scsi-0{{ found_folders.files[0].path | basename }}\s+/mnt/{{ found_folders.files[0].path | basename }}\s+'
        line: '/dev/disk/by-id/scsi-0{{ found_folders.files[0].path | basename }} /mnt/{{ hc_name }} ext4 discard,nofail,defaults 0 0'

    - name: Test fstab with mount -a command
      ansible.builtin.command: sudo mount -a
    # create new folder in mnt
    # /dev/disk/by-id/scsi-0HC_Volume_29139583 /mnt/HC_Volume_29139583 ext4 discard,nofail,defaults 0 0
    # edit this file in fstab
    # remount
    - name: Create gluster volume
      gluster.gluster.gluster_volume:
        state: present
        name: "{{ gfs_volume_name }}"
        bricks: /mnt/{{ hc_name }}/{{ gfs_host_name }}
        start_on_create: true
        force: true
        cluster:
          - 'data-01'
        options:
          { performance.quick-read: 'off',
            performance.read-ahead: 'off',
            performance.io-cache: 'off',
            performance.stat-prefetch: 'off',
            network.remote-dio: 'enable',
            cluster.eager-lock: 'enable',
            cluster.quorum-type: 'auto',
            cluster.server-quorum-type: 'server',
            cluster.data-self-heal-algorithm: 'full',
            cluster.locking-scheme: 'granular',
            features.shard: 'on',
            user.cifs: 'off',
          }
      become: true
