---
- name: add iptables for rs-web
  hosts: rs-web
  gather_facts: false
  vars_files:
    - "../vars/index.yml"
  remote_user: "{{ username }}"
  become: true
  # hetzner_network_ip_subnet
  tasks:
    # INTERNAL
    - include_tasks: tasks/iptables/initiate.yml
    - include_tasks: tasks/iptables/incoming-ssh.yml
      vars:
        interface: "en+"
        jump: "ACCEPT"

    - include_tasks: tasks/iptables/outgoing-ssh.yml
      vars:
        interface: "en+"
        jump: "ACCEPT"

    - include_tasks: tasks/iptables/postgres-subnet-port.yml
      vars:
        port: 5432
        subnet: "{{ hetzner_network_ip_subnet }}"
        interface: "en+"
        jump: "ACCEPT"

    - include_tasks: tasks/iptables/incoming-http.yml
      vars:
        interface: "en+"
        jump: "ACCEPT"

    - include_tasks: tasks/iptables/outgoing-http.yml
      vars:
        interface: "en+"
        jump: "ACCEPT"

    # EXTERNAL
    - include_tasks: tasks/iptables/outgoing-postgres.yml
      vars:
        interface: "en+"
        jump: "ACCEPT"
    - include_tasks: tasks/iptables/incoming-ssh.yml
      vars:
        interface: "et+"
        jump: "ACCEPT"

    - include_tasks: tasks/iptables/outgoing-ssh.yml
      vars:
        interface: "et+"
        jump: "ACCEPT"
    - include_tasks: tasks/iptables/tcp-dos.yml
      vars:
        jump: "ACCEPT"
        limit: 100/min
        limit_burst: 200
    - include_tasks: tasks/iptables/dropnull.yml
    # - include_tasks: tasks/iptables/dropfragmented.yml
    # - include_tasks: tasks/iptables/forcesyn.yml
    - include_tasks: tasks/iptables/dropxmas.yml
    - include_tasks: tasks/iptables/logging.yml
    - include_tasks: tasks/iptables/chain-policies.yml
    - include_tasks: tasks/iptables/incoming-http.yml
      vars:
        interface: "et+"
        jump: "ACCEPT"

    - include_tasks: tasks/iptables/outgoing-http.yml
      vars:
        interface: "et+"
        jump: "ACCEPT"

    - include_tasks: tasks/iptables/incoming-https.yml
      vars:
        interface: "et+"
        jump: "ACCEPT"

    - include_tasks: tasks/iptables/outgoing-https.yml
      vars:
        interface: "et+"
        jump: "ACCEPT"

    - include_tasks: tasks/iptables/sendmail.yml
      vars:
        interface: "et+"
        jump: "ACCEPT"

    - include_tasks: tasks/iptables/imap.yml
      vars:
        interface: "et+"
        jump: "ACCEPT"

    - include_tasks: tasks/iptables/imaps.yml
      vars:
        interface: "et+"
        jump: "ACCEPT"

    - include_tasks: tasks/iptables/pop3.yml
      vars:
        interface: "et+"
        jump: "ACCEPT"

    - include_tasks: tasks/iptables/pop3s.yml
      vars:
        interface: "et+"
        jump: "ACCEPT"
