---
- name: Restart all servers
  hosts: all
  gather_facts: false
  vars_files:
    - "../vars/index.yml"
  remote_user: "{{ username }}"

  tasks:
    - name: Pause for 5 minutes to build app cache
      ansible.builtin.pause:
        minutes: 1

    - name: Reboot a slow machine that might have lots of updates to apply
      ansible.builtin.reboot:
        reboot_timeout: 3600
      become: true
