---
- name: Setup prometheus
  hosts: manager*
  gather_facts: false
  vars_files:
    - "../vars/index.yml"
  remote_user: "{{ username }}"

  tasks:
  ### we need to add this config to manager
    - name: Create config foo (from a file on the control machine)
      community.docker.docker_config:
        name: node_exporter_entrypoint
        data: "{{ lookup('file', '../configs/node_exporter_entrypoint') | b64encode }}"
        data_is_b64: true
        state: present
    - name: Rnsures etc/prometheus exists
      ansible.builtin.file:
        path: "/etc/prometheus"
        state: directory
        mode: "0744"
      become: true

    - name: Copy prometheus config
      ansible.builtin.copy:
        src: "../apps/prometheus/prometheus.yml"
        dest: /etc/prometheus/prometheus.yml
        mode: '0644'
      become: true

    - name: Copy prometheus stack config
      ansible.builtin.copy:
        src: "../apps/prometheus/prometheus-stack.yml"
        dest: ~/prometheus-stack.yml
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: '0644'

    - name: Replace node labels with new labels
      community.docker.docker_node:
        hostname: "{{ inventory_hostname.split('-')[:2] | join('-') }}"
        labels:
          prometheus.data: "true"
        labels_state: merge

    - name: Deploy stack from a compose file
      community.docker.docker_stack:
        state: present
        name: prometheus
        compose:
          - /home/swarm/prometheus-stack.yml
