---
- name: Setup gluster client
  hosts: all,!data*
  vars_files:
    - "../vars/index.yml"
  strategy: free
  remote_user: "{{ unix_user }}"
  tasks:
    - name: Create /mnt/storage-pool directory
      ansible.builtin.file:
        path: /mnt/{{ gfs_mount_name }}
        state: directory
        owner: "{{ unix_user }}"
        group: "{{ unix_user }}"
        mode: '0744'
      become: true

    - name: Append mount to /etc/fstab for persistent mount
      ansible.builtin.lineinfile:
        path: /etc/fstab
        line: "data-01:/{{ gfs_volume_name }} /mnt/{{ gfs_mount_name }} glusterfs defaults,_netdev,x-systemd.automount 0 0"
      become: true

    - name: Test fstab with mount -a command
      ansible.builtin.command: sudo mount -a