---
- name: Setup traefik
  hosts: manager*
  gather_facts: false
  vars_files:
    - "../vars/index.yml"
    - "../vars/sensitive-apps.yml"
  remote_user: "{{ unix_user }}"

  tasks:
    - name: Rnsures etc/traefik exists
      ansible.builtin.file:
        path: "/etc/traefik"
        state: directory
        mode: "0744"
      become: true

    - name: Create config from template
      ansible.builtin.template:
        src: "../apps/traefik/traefik.yml.j2"
        dest: /etc/traefik/traefik.yml
        mode: '0644'
      vars:
        traefik_domain: "{{ swarm_sd }}.{{ root_dns }}"
      become: true
      
    - name: Rnsures /mnt/storage-pool/certs exists
      ansible.builtin.file:
        path: "/mnt/storage-pool/certs"
        state: directory
        owner: "{{ unix_user }}"
        group: "{{ unix_user }}"
        mode: "0744"
      become: true

    - name: Copy certs
      ansible.builtin.copy:
        src: "../certs/acme.json"
        dest: /mnt/storage-pool/certs/acme.json
        owner: "{{ unix_user }}"
        group: "{{ unix_user }}"
        mode: '0600'

    - name: Copy traefik stack config
      ansible.builtin.copy:
        src: "../apps/traefik/traefik-stack.yml"
        dest: ~/traefik-stack.yml
        owner: "{{ unix_user }}"
        group: "{{ unix_user }}"
        mode: '0644'

    # - name: Add tag to manager
    #   ansible.builtin.command:
    #     cmd: docker node update --label-add traefik-public.certificates=true {{ inventory_hostname.split('-')[:2] | join('-') }}

    - name: Replace node labels with new labels
      community.docker.docker_node:
        hostname: "{{ inventory_hostname.split('-')[:2] | join('-') }}"
        labels:
          traefik-public.certificates: "true"
        labels_state: merge

    - name: Generate encrypted password
      ansible.builtin.command: openssl passwd -apr1 {{ admin_auth_pass }}
      register: encrypted_password
      changed_when: encrypted_password.rc != 0

    - name: Deploy stack from a compose file
      community.docker.docker_stack:
        state: present
        name: traefik
        compose:
          - /home/swarm/traefik-stack.yml
      environment:
        HASHED_PASSWORD: "{{ encrypted_password.stdout }}"
        TR_USER: "{{ admin_auth_user }}"
