---
- name: Write secrets to docker
  hosts: manager*
  gather_facts: false
  vars_files:
    - "../vars/index.yml"
  remote_user: "{{ unix_user }}"
  vars:
    secrets_file: "../vars/sensitive-apps.yml"
  tasks:
    - name: Load secrets from file
      ansible.builtin.include_vars:
        file: "{{ secrets_file }}"
        name: secrets

    # - name: debug
    #   debug: msg="{{ secrets }}"
    - name: Add secrets to Docker Swarm
      community.docker.docker_secret:
        name: "{{ item.key }}"
        data: "{{ item.value }}"
      no_log: true
      with_dict: "{{ secrets }}"
