---
- name: NAME
  hosts: rs-dba
  gather_facts: false
  vars_files:
    - "../vars/index.yml"
  remote_user: "{{ username }}"

  tasks:
    - name: 05 22 * * * /git/regshort-back/.venv/bin/python3 /git/regshort-back/app/download_data.py
      ansible.builtin.cron:
        name: "download_data.py"
        minute: "05"
        hour: "22"
        job: "/git/regshort-back/.venv/bin/python3 /git/regshort-back/app/download_data.py"

    - name: 00 01 * * * /git/regshort-back/.venv/bin/python3 /git/regshort-back/app/download_data.py
      ansible.builtin.cron:
        name: "download_data.py 2"
        minute: "00"
        hour: "01"
        job: "/git/regshort-back/.venv/bin/python3 /git/regshort-back/app/download_data.py"

    - name: 15 01 * * * /git/regshort-back/.venv/bin/python3 /git/regshort-back/app/merge_data.py
      ansible.builtin.cron:
        name: "merge_data.py"
        minute: "15"
        hour: "01"
        job: "/git/rs-back/.venv/bin/python3 /git/rs-back/app/merge_data.py"

    - name: 30 06 * * * . /git/rs-back/.venv/bin/activate && /git/rs-back/.venv/bin/python3 /git/rs-back/app/import_data.py && deactivate
      ansible.builtin.cron:
        name: "import_data.py"
        minute: "30"
        hour: "06"
        job: ". /git/rs-back/.venv/bin/activate && /git/rs-back/.venv/bin/python3 /git/rs-back/app/import_data.py && deactivate"

    - name: 30 07 * * * python3 /git/rs-pg2arrow/pg2arrow.py
      ansible.builtin.cron:
        name: "pg2arrow.py"
        minute: "30"
        hour: "07"
        job: "python3 /git/rs-pg2arrow/pg2arrow.py"

    - name: 45 07 * * * scp -i ~/.ssh/regshort_rsa /git/regshort-pg2arrow/*.arrow regshort@regshort-str:/git/regshort-streamer/.
      ansible.builtin.cron:
        name: "pg2arrow.py"
        minute: "30"
        hour: "07"
        job: "scp -i ~/.ssh/rsa_id /git/rs-pg2arrow/*.arrow regshort@rs-str:/git/rs-streamer/."

    - name: 00 08 * * * cd /git/regshort-b2f/ && /home/regshort/.nvm/versions/node/v18.13.0/bin/ts-node b2fSecs.ts
      ansible.builtin.cron:
        name: "b2fSecs.ts"
        minute: "00"
        hour: "08"
        job: "cd /git/regshort-b2f/ && /home/regshort/.nvm/versions/node/v18.13.0/bin/ts-node b2fSecs.ts"
      # 05 22 * * * /git/regshort-back/.venv/bin/python3 /git/regshort-back/app/download_data.py
      # 00 01 * * * /git/regshort-back/.venv/bin/python3 /git/regshort-back/app/download_data.py
      # 15 01 * * * /git/regshort-back/.venv/bin/python3 /git/regshort-back/app/merge_data.py
      # 30 06 * * * . /git/regshort-back/.venv/bin/activate && /git/regshort-back/.venbinv//python3 /git/regshort-back/app/import_data.py && deactivate
      # 30 07 * * * python3 /git/regshort-pg2arrow/pg2arrow.py
      # 45 07 * * * scp -i ~/.ssh/regshort_rsa /git/regshort-pg2arrow/*.arrow regshort@regshort-str:/git/regshort-streamer/.
      # 00 08 * * * cd /git/regshort-b2f/ && /home/regshort/.nvm/versions/node/v18.13.0/bin/ts-node b2fSecs.ts
