---
- name: setup pg2arrow
  hosts: rs-dba
  gather_facts: false
  vars_files:
    - "../vars/index.yml"
  vars:
    repo_name: rs-pg2arrow
  remote_user: "{{ username }}"
  tasks:
    - name: Install postgres packages
      ansible.builtin.apt:
        name:
          - libcairo2-dev
          - pkg-config
        state: present
      become: true

    - name: Install {{ repo_name }} python requirements
      ansible.builtin.pip:
        requirements: "{{ [app_dir, repo_name] | path_join }}/requirements.txt"

    - name: set DATABASE_URL in .env
      lineinfile:
        path: "{{ [app_dir, repo_name] | path_join }}/.env"
        regexp: "^DATABASE_URL="
        line: 'DATABASE_URL="postgresql://{{ username }}:{{ username }}@{{ hostvars["rs-dba"].private_ipv4 }}:5432/{{ username }}back"'
