---
- name: add node_env
  hosts: all
  gather_facts: false
  vars_files:
    - "../vars/index.yml"
  remote_user: "{{ username }}"
  strategy: free

  tasks:
    - name: add node_env
      lineinfile:
        path: /etc/environment
        line: "NODE_ENV=production"
      become: true
