---
- name: Copying ssh key and updating sudoers
  hosts: manager*
  vars_files:
    - "../vars/index.yml"

  gather_facts: false
  become: true
  remote_user: "root"
  strategy: free

  tasks:
    - name: Copy SSh Key | copying shh key to remote host
      ansible.posix.authorized_key:
        user: "{{ unix_user }}"
        state: present
        key: "{{ lookup('file', '../ssh/id_rsa.pub') }}"
