---
- name: Upload keys to github
  hosts: all
  gather_facts: true
  vars_files:
    - "../vars/index.yml"
    - "../vars/sensitive.yml"
  remote_user: "{{ username }}"
  strategy: free
  tasks:
    - name: Slurp hosts file
      slurp:
        src: ~/.ssh/id_rsa.pub
      register: slurped_key_b64
    - name: add ssh key to github
      community.general.github_key:
        name: "{{ 99999999 | random | to_uuid }}{{ inventory_hostname | regex_replace('^([^-]+-[^-]+).*', '\\1') }}{{ ansible_default_ipv4.address.split('.')[-1] }}"
        pubkey: "{{ slurped_key_b64.content | b64decode }}"
        token: "{{ github_access_token }}"
      retries: 3
